/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "stable_part_provider.h"

namespace ge {
Status ResolveStablePart(StablePartId id, std::string &output) {
  switch (id) {
    case StablePartId::kChkStatusMacro:
      output =
          "#define OM2_CHK_STATUS(expr, ...)            \\\n"
          "do {                                       \\\n"
          "  const aclError _chk_status = (expr);     \\\n"
          "  if (_chk_status != ACL_SUCCESS) {        \\\n"
          "    return _chk_status;                    \\\n"
          "  }                                        \\\n"
          "} while (false)\n";
      return SUCCESS;
    case StablePartId::kChkNotNullMacro:
      output =
          "#define OM2_CHK_NOTNULL(ptr, ...)            \\\n"
          "do {                                       \\\n"
          "  if ((ptr) == nullptr) {                  \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n";
      return SUCCESS;
    case StablePartId::kChkTrueMacro:
      output =
          "#define OM2_CHK_TRUE(expr, ...)              \\\n"
          "do {                                       \\\n"
          "  if (!(expr)) {                           \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n";
      return SUCCESS;
    case StablePartId::kGetAddrMacro:
      output =
          "#define GET_ADDR(mem_ptr, offset)   \\\n"
          "(reinterpret_cast<void *>(                 \\\n"
          "  reinterpret_cast<uintptr_t>(mem_ptr) +   \\\n"
          "  static_cast<uintptr_t>(offset)))\n";
      return SUCCESS;
    case StablePartId::kMakeGuardMacro:
      output = "#define OM2_MAKE_GUARD(var, callback) const ::om2::ScopeGuard const_guard_##var(callback)\n";
      return SUCCESS;
    case StablePartId::kInterfaceMacros:
      output =
          "#define OM2_CHK_STATUS(expr, ...)            \\\n"
          "do {                                       \\\n"
          "  const aclError _chk_status = (expr);     \\\n"
          "  if (_chk_status != ACL_SUCCESS) {        \\\n"
          "    return _chk_status;                    \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define OM2_CHK_NOTNULL(ptr, ...)            \\\n"
          "do {                                       \\\n"
          "  if ((ptr) == nullptr) {                  \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define OM2_CHK_TRUE(expr, ...)              \\\n"
          "do {                                       \\\n"
          "  if (!(expr)) {                           \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define OM2_CHK_RT(expr, ...)               \\\n"
          "do {                                       \\\n"
          "  const rtError_t _rt_err = (expr);        \\\n"
          "  if (_rt_err != RT_ERROR_NONE) {          \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define GET_ADDR(mem_ptr, offset)   \\\n"
          "(reinterpret_cast<void *>(                 \\\n"
          "  reinterpret_cast<uintptr_t>(mem_ptr) +   \\\n"
          "  static_cast<uintptr_t>(offset)))\n"
          "\n"
          "#define OM2_MAKE_GUARD(var, callback) const ::om2::ScopeGuard const_guard_##var(callback)\n";
      return SUCCESS;
    case StablePartId::kPointerHelpers:
      output =
          "template<typename T>\n"
          "inline T *PtrAdd(T *const ptr, const size_t max_buf_len, const size_t idx) {\n"
          "  if ((ptr != nullptr) && (idx < max_buf_len)) {\n"
          "    return reinterpret_cast<T *>(ptr + idx);\n"
          "  }\n"
          "  return nullptr;\n"
          "}\n"
          "template<typename TI, typename TO>\n"
          "inline TO *PtrToPtr(TI *const ptr) {\n"
          "  return reinterpret_cast<TO *>(ptr);\n"
          "}\n"
          "inline uint64_t PtrToValue(const void *const ptr) {\n"
          "  return static_cast<uint64_t>(reinterpret_cast<uintptr_t>(ptr));\n"
          "}\n"
          "inline void *ValueToPtr(const uint64_t value) {\n"
          "  return reinterpret_cast<void *>(static_cast<uintptr_t>(value));\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kInterfacePointerHelpers:
      output =
          "template<typename T>\n"
          "inline T *PtrAdd(T *const ptr, const size_t max_buf_len, const size_t idx) {\n"
          "  if ((ptr != nullptr) && (idx < max_buf_len)) {\n"
          "    return reinterpret_cast<T *>(ptr + idx);\n"
          "  }\n"
          "  return nullptr;\n"
          "}\n"
          "template<typename TI, typename TO>\n"
          "inline TO *PtrToPtr(TI *const ptr) {\n"
          "  return reinterpret_cast<TO *>(ptr);\n"
          "}\n"
          "inline uint64_t PtrToValue(const void *const ptr) {\n"
          "  return static_cast<uint64_t>(reinterpret_cast<uintptr_t>(ptr));\n"
          "}\n"
          "inline void *ValueToPtr(const uint64_t value) {\n"
          "  return reinterpret_cast<void *>(static_cast<uintptr_t>(value));\n"
          "}\n"
          "inline uint64_t PtrToU64(const void *ptr) {\n"
          "  return static_cast<uint64_t>(reinterpret_cast<uintptr_t>(ptr));\n"
          "}\n"
          "\n"
          "extern \"C\" {\n"
          "struct Om2Tensor {\n"
          "  uint64_t device_address;\n"
          "  uint64_t size;\n"
          "  int32_t data_type;\n"
          "  int32_t format;\n"
          "  const int64_t* shape_dims;\n"
          "  uint64_t shape_dims_num;\n"
          "};\n"
          "}\n"
          "\n"
          "template<typename... Args>\n"
          "inline std::vector<uint64_t> FlattenHostArgs(Args&&... args) {\n"
          "  std::vector<uint64_t> buf;\n"
          "  auto append_arg = [&](auto&& arg) {\n"
          "    using T = std::decay_t<decltype(arg)>;\n"
          "    if constexpr (std::is_pointer_v<T>) {\n"
          "      buf.push_back(reinterpret_cast<uint64_t>(arg));\n"
          "    } else if constexpr (std::is_same_v<T, Om2Tensor>) {\n"
          "      buf.push_back(arg.device_address);\n"
          "    } else if constexpr (std::is_same_v<T, std::vector<int64_t>>) {\n"
          "      for (auto d : arg) buf.push_back(static_cast<uint64_t>(d));\n"
          "    } else if constexpr (std::is_integral_v<T>) {\n"
          "      buf.push_back(static_cast<uint64_t>(arg));\n"
          "    } else {\n"
          "      static_assert(sizeof(T) == 0, \"Unsupported type in FlattenHostArgs\");\n"
          "    }\n"
          "  };\n"
          "  (append_arg(std::forward<Args>(args)), ...);\n"
          "  return buf;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kFlattenHostArgs:
      output =
          "extern \"C\" {\n"
          "struct Om2Tensor {\n"
          "  uint64_t device_address;\n"
          "  uint64_t size;\n"
          "  int32_t data_type;\n"
          "  int32_t format;\n"
          "  const int64_t* shape_dims;\n"
          "  uint64_t shape_dims_num;\n"
          "};\n"
          "}\n"
          "\n"
          "template<typename... Args>\n"
          "inline std::vector<uint64_t> FlattenHostArgs(Args&&... args) {\n"
          "  std::vector<uint64_t> buf;\n"
          "  auto append_arg = [&](auto&& arg) {\n"
          "    using T = std::decay_t<decltype(arg)>;\n"
          "    if constexpr (std::is_pointer_v<T>) {\n"
          "      buf.push_back(reinterpret_cast<uint64_t>(arg));\n"
          "    } else if constexpr (std::is_same_v<T, Om2Tensor>) {\n"
          "      buf.push_back(arg.device_address);\n"
          "    } else if constexpr (std::is_same_v<T, std::vector<int64_t>>) {\n"
          "      for (auto d : arg) buf.push_back(static_cast<uint64_t>(d));\n"
          "    } else if constexpr (std::is_integral_v<T>) {\n"
          "      buf.push_back(static_cast<uint64_t>(arg));\n"
          "    } else {\n"
          "      static_assert(sizeof(T) == 0, \"Unsupported type in FlattenHostArgs\");\n"
          "    }\n"
          "  };\n"
          "  (append_arg(std::forward<Args>(args)), ...);\n"
          "  return buf;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kScopeGuard:
      output =
          "class ScopeGuard {\n"
          "  public:\n"
          "    ScopeGuard(const ScopeGuard &) = delete;\n"
          "    ScopeGuard &operator=(const ScopeGuard &) = delete;\n"
          "\n"
          "    explicit ScopeGuard(const std::function<void()> &on_exit_scope)\n"
          "        : on_exit_scope_(on_exit_scope) {}\n"
          "\n"
          "    ~ScopeGuard() {\n"
          "      if (on_exit_scope_) {\n"
          "        try {\n"
          "          on_exit_scope_();\n"
          "        } catch (std::bad_function_call &) {\n"
          "        } catch (...) {\n"
          "        }\n"
          "      }\n"
          "    }\n"
          "\n"
          "  private:\n"
          "    std::function<void()> on_exit_scope_;\n"
          "};\n";
      return SUCCESS;
    case StablePartId::kReadBinaryFileToBuffer:
      output =
          "BinaryBuffer ReadBinaryFileToBuffer(const std::string &file_path) {\n"
          "  BinaryBuffer result;\n"
          "  std::ifstream file(file_path, std::ios::binary | std::ios::ate);\n"
          "  if (!file.is_open()) {\n"
          "    return result;\n"
          "  }\n"
          "  std::streamsize file_size = file.tellg();\n"
          "  if (file_size <= 0) {\n"
          "    return result;\n"
          "  }\n"
          "  result.size = static_cast<size_t>(file_size);\n"
          "  result.data = std::make_unique<uint8_t[]>(result.size);\n"
          "  file.seekg(0, std::ios::beg);\n"
          "  file.read(reinterpret_cast<char *>(result.data.get()), result.size);\n"
          "  if (!file.good()) {\n"
          "    file.close();\n"
          "    result.data.reset();\n"
          "    result.size = 0;\n"
          "  }\n"
          "  return result;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kGenerateJsonFile:
      output =
          "aclError GenerateJsonFile(const AicpuRegisterInfo &register_info, std::string &json_path) {\n"
          "  using namespace std::chrono;\n"
          "  int64_t cur_timestamp = duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();\n"
          "  json_path = \"/tmp/temp_ops_info_\" + std::to_string(cur_timestamp) + \".json\";\n"
          "  std::string json_data_format = R\"(\n"
          "{\n"
          "    \"%s\":{\n"
          "        \"opInfo\":{\n"
          "            \"opKernelLib\":\"%s\",\n"
          "            \"kernelSo\":\"%s\",\n"
          "            \"functionName\":\"%s\"\n"
          "        }\n"
          "    }\n"
          "}\n"
          ")\";\n"
          "  char json_data[kMaxJsonFileLen];\n"
          "  auto ret = snprintf_s(json_data, kMaxJsonFileLen, kMaxJsonFileLen - 1U, json_data_format.c_str(),\n"
          "                        register_info.op_type, register_info.op_kernel_lib, register_info.so_name,\n"
          "                        register_info.kernel_name);\n"
          "  OM2_CHK_TRUE(ret >= 0);\n"
          "  std::ofstream ofs(json_path.c_str(), std::ios::trunc);\n"
          "  OM2_CHK_TRUE(ofs);\n"
          "  ofs << json_data;\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kLoadAndRunExternalApis:
      output =
          "aclError Om2ModelCreate(om2::Om2ModelHandle *model_handle, aclmdlRI *rt_model_handle, "
          "const char **bin_files, const void **bin_data, size_t *bin_size, int bin_num, void **constants, "
          "void *work_ptr, uint64_t *session_id, uint32_t model_id, void *instance_handle) {\n"
          "  if ((model_handle == nullptr) || (rt_model_handle == nullptr) || (*model_handle != nullptr)) {\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  auto *obj = new om2::Om2Model(bin_files, bin_data, bin_size, bin_num, constants, work_ptr, session_id,\n"
          "                                model_id, instance_handle);\n"
          "  if (obj == nullptr) {\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  auto ret = obj->InitResources();\n"
          "  if (ret != ACL_SUCCESS) {\n"
          "    delete obj;\n"
          "    return ret;\n"
          "  }\n"
          "  ret = obj->RegisterKernels();\n"
          "  if (ret != ACL_SUCCESS) {\n"
          "    delete obj;\n"
          "    return ret;\n"
          "  }\n"
          "  *model_handle = reinterpret_cast<om2::Om2ModelHandle>(obj);\n"
          "  *rt_model_handle = obj->GetRtModelHandle();\n"
          "  return ACL_SUCCESS;\n"
          "}\n"
          "\n"
          "aclError Om2ModelLoad(om2::Om2ModelHandle *model_handle) {\n"
          "  if ((model_handle == nullptr) || (*model_handle == nullptr)) {\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  return static_cast<om2::Om2Model*>(*model_handle)->Load();\n"
          "}\n"
          "\n"
          "aclError Om2ModelRunAsync(om2::Om2ModelHandle *model_handle, aclrtStream stream, int input_count, "
          "void **input_data, int output_count, void **output_data) {\n"
          "  return static_cast<om2::Om2Model*>(*model_handle)->RunAsync(stream, input_count, input_data, output_count, "
          "output_data);\n"
          "}\n"
          "\n"
          "aclError Om2ModelRun(om2::Om2ModelHandle *model_handle, int input_count, void **input_data, int output_count, "
          "void **output_data, int32_t stream_sync_timeout) {\n"
          "  return static_cast<om2::Om2Model*>(*model_handle)->Run(input_count, input_data, output_count, output_data, stream_sync_timeout);\n"
          "}\n"
          "\n"
          "aclError Om2ModelDestroy(om2::Om2ModelHandle *model_handle) {\n"
          "  delete static_cast<om2::Om2Model*>(*model_handle);\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kInterfaceDumpApis:
      output =
          "struct Om2TaskIoEntry {\n"
          "  const struct Om2Tensor *tensor;\n"
          "  uint64_t offset;\n"
          "};\n"
          "\n"
          "struct Om2TaskInfo {\n"
          "  const char* op_name;\n"
          "  const char* op_type;\n"
          "  uint32_t task_id;\n"
          "  uint32_t stream_id;\n"
          "  uint32_t context_id;\n"
          "  uint32_t thread_id;\n"
          "  uint64_t op_desc_id;\n"
          "  uintptr_t args_base;\n"
          "  uint64_t args_size;\n"
          "  uint64_t input_num;\n"
          "  const struct Om2TaskIoEntry* inputs;\n"
          "  uint32_t output_num;\n"
          "  const struct Om2TaskIoEntry* outputs;\n"
          "  uint32_t workspace_num;\n"
          "  const uint64_t* workspace_addrs;\n"
          "  const uint64_t* workspace_sizes;\n"
          "  uint32_t task_type;\n"
          "  void* stream;\n"
          "  uint32_t is_raw_address;\n"
          "};\n"
          "\n"
          "__attribute__((weak)) int32_t ReportTaskInfo(uint32_t model_id,\n"
          "                                              void* instance_handle,\n"
          "                                              const struct Om2TaskInfo* task_info,\n"
          "                                              const void* extended_attrs,\n"
          "                                              size_t extended_attrs_size);\n"
          "\n"
          "__attribute__((weak)) int32_t IsDataDumpEnabled(uint32_t model_id,\n"
          "                                                      void* instance_handle,\n"
          "                                                      const char* op_name,\n"
          "                                                      uint8_t* is_data_dump);\n";
      return SUCCESS;
    case StablePartId::kLoadAndRunDumpHelpers:
      output =
          "Om2Tensor BuildOm2Tensor(void *device_address, uint64_t size, int32_t data_type,\n"
          "                         int32_t format, std::vector<int64_t> &shape_dims) {\n"
          "  Om2Tensor tensor{};\n"
          "  tensor.device_address = PtrToU64(device_address);\n"
          "  tensor.size = size;\n"
          "  tensor.data_type = data_type;\n"
          "  tensor.format = format;\n"
          "  tensor.shape_dims = shape_dims.data();\n"
          "  tensor.shape_dims_num = static_cast<uint64_t>(shape_dims.size());\n"
          "  return tensor;\n"
          "}\n"
          "\n"
          "aclError AssembleOm2TaskInfo(Om2TaskInfo *task_info, const char *op_name, const char *op_type,\n"
          "                             uint32_t task_id, uint32_t stream_id, uint64_t op_desc_id,\n"
          "                             uintptr_t args_base, uint64_t args_size,\n"
          "                             const Om2TaskIoEntry *inputs, uint64_t input_num,\n"
          "                             const Om2TaskIoEntry *outputs, uint32_t output_num,\n"
          "                             const uint64_t *workspace_addrs, const uint64_t *workspace_sizes,\n"
          "                             uint32_t workspace_num, uint32_t task_type, void *stream,\n"
          "                             uint32_t is_raw_address = 0U) {\n"
          "  task_info->op_name = op_name;\n"
          "  task_info->op_type = op_type;\n"
          "  task_info->task_id = task_id;\n"
          "  task_info->stream_id = stream_id;\n"
          "  task_info->context_id = 0U;\n"
          "  task_info->thread_id = 0U;\n"
          "  task_info->op_desc_id = op_desc_id;\n"
          "  task_info->args_base = args_base;\n"
          "  task_info->args_size = args_size;\n"
          "  task_info->input_num = input_num;\n"
          "  task_info->inputs = inputs;\n"
          "  task_info->output_num = output_num;\n"
          "  task_info->outputs = outputs;\n"
          "  task_info->workspace_num = workspace_num;\n"
          "  task_info->workspace_addrs = workspace_addrs;\n"
          "  task_info->workspace_sizes = workspace_sizes;\n"
          "  task_info->task_type = task_type;\n"
          "  task_info->stream = stream;\n"
          "  task_info->is_raw_address = is_raw_address;\n"
          "  return ACL_SUCCESS;\n"
          "}\n"
          "\n"
          "aclError ReportLaunchedOm2Task(const char *op_name, const char *op_type, uint64_t op_desc_id,\n"
          "                               uintptr_t args_base, uint64_t args_size,\n"
          "                               const std::vector<Om2TaskIoEntry> &inputs,\n"
          "                               const std::vector<Om2TaskIoEntry> &outputs,\n"
          "                               const std::vector<uint64_t> &workspace_addrs,\n"
          "                               const std::vector<uint64_t> &workspace_sizes,\n"
          "                               uint32_t task_type, void *stream,\n"
          "                               uint32_t model_id, void *instance_handle,\n"
          "                               uint32_t is_raw_address = 0U) {\n"
          "  uint32_t task_id = 0U;\n"
          "  OM2_CHK_RT(rtsGetThreadLastTaskId(&task_id));\n"
          "\n"
          "  uint32_t stream_id = 0U;\n"
          "  OM2_CHK_STATUS(aclrtStreamGetId(stream, reinterpret_cast<int32_t *>(&stream_id)));\n"
          "\n"
          "  OM2_CHK_TRUE(workspace_addrs.size() == workspace_sizes.size());\n"
          "\n"
          "  Om2TaskInfo task_info{};\n"
          "  OM2_CHK_STATUS(AssembleOm2TaskInfo(&task_info, op_name, op_type, task_id, stream_id, op_desc_id,\n"
          "                                      args_base, args_size,\n"
          "                                      inputs.data(), static_cast<uint64_t>(inputs.size()),\n"
          "                                      outputs.data(), static_cast<uint32_t>(outputs.size()),\n"
          "                                      workspace_addrs.empty() ? nullptr : workspace_addrs.data(),\n"
          "                                      workspace_sizes.empty() ? nullptr : workspace_sizes.data(),\n"
          "                                      static_cast<uint32_t>(workspace_addrs.size()),\n"
          "                                      task_type, stream, is_raw_address));\n"
          "  if (ReportTaskInfo != nullptr && instance_handle != nullptr) {\n"
          "    OM2_CHK_STATUS(ReportTaskInfo(model_id, instance_handle, &task_info, nullptr, 0U));\n"
          "  }\n"
          "  return ACL_SUCCESS;\n"
          "}\n"
          "\n"
          "uint8_t GetIsDataDump(const char *op_name, uint32_t model_id, void *instance_handle) {\n"
          "  if (IsDataDumpEnabled != nullptr && instance_handle != nullptr) {\n"
          "    uint8_t is_data_dump = 0U;\n"
          "    auto ret = IsDataDumpEnabled(model_id, instance_handle, op_name, &is_data_dump);\n"
          "    return ret == 0 ? is_data_dump : 0U;\n"
          "  }\n"
          "  return 0U;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kCreateLabelListForLabelSwitch:
      output = 
              "aclError Om2Model::CreateLabelListForLabelSwitch(uint32_t op_index, std::vector<uint32_t> label_list_indexs)\n"
              "{\n"
              "  label_switch_label_list_[op_index] = nullptr;\n"
              "  uint32_t label_used_size = label_list_indexs.size();\n"
              "  label_used_.resize(label_used_size, nullptr);\n"
              "  for (uint32_t i = 0; i < label_used_size; i++) {\n"
              "    label_used_[i] = label_list_[label_list_indexs[i]];\n"
              "  }\n"
              "  OM2_CHK_STATUS(aclrtCreateLabelList(label_used_.data(), label_used_.size(), &(label_switch_label_list_[op_index])));\n"
              "  return ACL_SUCCESS;\n"
              "}\n";
      return SUCCESS;
    case StablePartId::kCreateLabelListForLabelGotoEx:
      output =
              "aclError Om2Model::CreateLabelListForLabelGotoEx(uint32_t op_index, uint32_t label_index)\n"
              "{\n"
              "  label_goto_ex_label_list_[op_index] = nullptr;\n"
              "  const auto it = label_goto_args_.find(label_index);\n"
              "  if (it != label_goto_args_.cend()) {\n"
              "    label_goto_ex_label_list_[op_index] = it->second.first;\n"
              "  } else {\n"
              "    label_used_.resize(1, nullptr);\n"
              "    label_used_[0] = label_list_[static_cast<size_t>(label_index)];\n"
              "    OM2_CHK_STATUS(aclrtCreateLabelList(label_used_.data(), label_used_.size(), &(label_goto_ex_label_list_[op_index])));\n"
              "    label_goto_args_[label_index] = {label_goto_ex_label_list_[op_index], static_cast<uint32_t>(sizeof(rtLabelDevInfo))};\n"
              "  }\n"
              "  return ACL_SUCCESS;\n"
              "}\n";
      return SUCCESS;
    default:
      output.clear();
      return FAILED;
  }
}
}  // namespace ge
